/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as ProtectedImport } from './routes/protected'
import { Route as TestRouteImport } from './routes/test/route'
import { Route as IndexImport } from './routes/index'
import { Route as TestIndexImport } from './routes/test/index'
import { Route as TestTestIdImport } from './routes/test/$testId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => rootRoute,
} as any)

const TestRouteRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestIndexRoute = TestIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRouteRoute,
} as any)

const TestTestIdRoute = TestTestIdImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRoute
    }
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdImport
      parentRoute: typeof TestRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexImport
      parentRoute: typeof TestRouteImport
    }
  }
}

// Create and export the route tree

interface TestRouteRouteChildren {
  TestTestIdRoute: typeof TestTestIdRoute
  TestIndexRoute: typeof TestIndexRoute
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestTestIdRoute: TestTestIdRoute,
  TestIndexRoute: TestIndexRoute,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRouteRouteWithChildren
  '/protected': typeof ProtectedRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/test/$testId': typeof TestTestIdRoute
  '/test/': typeof TestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protected': typeof ProtectedRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/test/$testId': typeof TestTestIdRoute
  '/test': typeof TestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/test': typeof TestRouteRouteWithChildren
  '/protected': typeof ProtectedRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/test/$testId': typeof TestTestIdRoute
  '/test/': typeof TestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/protected'
    | '/signin'
    | '/signup'
    | '/test/$testId'
    | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/protected' | '/signin' | '/signup' | '/test/$testId' | '/test'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/protected'
    | '/signin'
    | '/signup'
    | '/test/$testId'
    | '/test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRouteRoute: typeof TestRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRouteRoute: TestRouteRouteWithChildren,
  ProtectedRoute: ProtectedRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/test",
        "/protected",
        "/signin",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/test": {
      "filePath": "test/route.tsx",
      "children": [
        "/test/$testId",
        "/test/"
      ]
    },
    "/protected": {
      "filePath": "protected.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/test/$testId": {
      "filePath": "test/$testId.tsx",
      "parent": "/test"
    },
    "/test/": {
      "filePath": "test/index.tsx",
      "parent": "/test"
    }
  }
}
ROUTE_MANIFEST_END */
